ViewModels/EditViewModel.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace FastDynamicForms.ViewModels
{
    public class EditViewModel
    {
        public string Name { get; set; }

        public object Entity { get; set; }

        /// <summary>
        /// Key: property name
        /// Value: property value
        /// </summary>
        public Dictionary<string, object> Properties { get; set; } = new Dictionary<string, object>();
    }
}

ViewModels/ListItemViewModel.cs
using System.Collections.Generic;
using System.Reflection;

namespace FastDynamicForms.ViewModels
{
    public class ListItemViewModel
    {
        private readonly object model;

        public ListItemViewModel(object model)
        {
            this.model = model;
        }

        /// <summary>
        /// Enumerates model properties returning KeyValuePair with key of proprty info and value of property value
        /// </summary>
        public IEnumerator<KeyValuePair<PropertyInfo, object>> GetEnumerator()
        {
            foreach (PropertyInfo propertyInfo in model.GetType().GetProperties())
            {
                object value = propertyInfo.GetValue(model);
                yield return new KeyValuePair<PropertyInfo, object>(propertyInfo, value);
            }
        }
    }
}

ViewModels/ListItemsViewModel.cs
using System;
using System.Collections.Generic;
using System.Text;

namespace FastDynamicForms.ViewModels
{
    public class ListItemsViewModel
    {
        public List<object> PropertyValues { get; set; } = new List<object>();
    }
}

ViewModels/RegisteredModelsViewModel.cs
using System.Collections.Generic;

namespace FastDynamicForms.ViewModels
{
    public class RegisteredModelsViewModel 
    {
        public string Name { get; set; }
        public List<string> PropertyNames { get; set; } = new List<string>();
        public List<ListItemViewModel> Items { get; set; } = new List<ListItemViewModel>();

        /// <summary>
        /// Should be empty instance. Used for display attributes
        /// </summary>
        public object EntityForDisplay { get; set; }
    }
}

Controllers/FastDynamicFormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using FastDynamicForms.Core.Models;
using FastDynamicForms.ViewModels;
using FastDynamicForms.Utilities;

namespace FastDynamicForms.Controllers
{
    public class FastDynamicFormsController : Controller
    {
        private readonly DbContext context;

        public FastDynamicFormsController(DbContext context)
        {
            this.context = context;
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Save(object model)
        {
            if (ModelState.IsValid)
            {
                EntityUtilities.SaveOrUpdateEntity(model, context);
            }
            else
            {
                EditViewModel viewModel = EntityUtilities.GetEditViewModel(model, context);
                return View("Edit", viewModel);
            }

            return RedirectToAction("List", new { modelTypeName = model.GetType().Name });
        }

        public IActionResult Create(string modelTypeName)
        {
            EditViewModel model = EntityUtilities.GetEmptyEditViewModel(modelTypeName, context);
            return View("Edit", model);
        }

        public IActionResult Edit(int id, string modelTypeName)
        {
            object entity = EntityUtilities.GetEntity(context, id, modelTypeName);
            EditViewModel model = EntityUtilities.GetEditViewModel(entity, context);

            return View(model);
        }

        //todo move logic out of controller
        public IActionResult List(string modelTypeName)
        {
            ModelsContainer container = Singleton<ModelsContainer>.Instance;

            var modelType = container.ModelTypes.Select(x => x.Key)
                .FirstOrDefault(x => x.Name == modelTypeName);
            if (modelType == null)
                throw new ArgumentException($"Registered model with name of \"{modelTypeName}\" not found");

            var viewModel = new RegisteredModelsViewModel()
            {
                Name = modelType.Name,
                EntityForDisplay = Activator.CreateInstance(modelType)
            };
            
            IQueryable dbSet = (IQueryable)EntityUtilities.GetEntityQuery(context, modelType);
            foreach (object dbSetItem in dbSet)
            {
                ListItemViewModel listItem = new ListItemViewModel(dbSetItem);
                viewModel.Items.Add(listItem);
            }
            viewModel.PropertyNames = modelType.GetProperties().Select(x => x.Name).ToList();

            return View(viewModel);
        }

        //todo move logic out of controller
        public IActionResult Index()
        {
            ModelsContainer container = Singleton<ModelsContainer>.Instance;
            var viewModels = new List<RegisteredModelsViewModel>();

            viewModels.AddRange(container.ModelTypes.Select(x => new RegisteredModelsViewModel()
            {
                Name = x.Key.Name
            }));

            return View(viewModels);
        }
    }
}

Views/FastDynamicForms/Edit.cshtml
@using FastDynamicForms.Extensions

@model FastDynamicForms.ViewModels.EditViewModel
@{
    Type modelType = Model.Entity.GetType();
}

<h1>@Model.Name</h1>

<div class="row">
    <div class="col-md-4">
        @using (Html.BeginForm("Save", "FastDynamicForms", FormMethod.Post))
        {
            @Html.AntiForgeryToken()
            <input type="hidden" id="ModelTypeName" name="ModelTypeName" value="@Model.Name" />
            @foreach (var item in Model.Properties)
            {
                //we use partials to change @model type in view
                //this CAN'T be done dynamically, so we trick view engine by creating partial view with required @model type
                //this is necessary because it's only way for view engine to catch attributes on models
                if (modelType.GetProperty(item.Key).IsNavigationalProperty())
                {
                    @Html.Partial("_NavigationPropertyPartial", Model.Entity, new ViewDataDictionary(this.ViewData) { { "PropertyName", item.Key }, { "SelectList", item.Value } })
                }
                else if (modelType.GetProperty(item.Key).IsPrimaryKey())
                {
                    @Html.Partial("_PrimaryKeyPartial", Model.Entity, new ViewDataDictionary(this.ViewData) { { "PropertyName", item.Key } })
                }
                else
                {
                    @Html.Partial("_PropertyPartial", Model.Entity, new ViewDataDictionary(this.ViewData) { { "PropertyName", item.Key } })
                }
            }

            <button type="submit" class="btn btn-success">Save</button>
            @Html.ActionLink("Back", "List", "FastDynamicForms", new { modelTypeName = Model.Name }, new { @class = "btn btn-default" })
        }
    </div>
</div>

Views/FastDynamicForms/Index.cshtml
@model List<FastDynamicForms.ViewModels.RegisteredModelsViewModel>

<style>
    td {
        font-size: 20px;
    }
</style>

<table class="table">
    <thead>
        <tr>
            <th>Fast Dynamic Forms</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@Html.ActionLink(item.Name, "List", "FastDynamicForms", new { modelTypeName = item.Name })</td>
            </tr>
        }
    </tbody>
</table>

Views/FastDynamicForms/List.cshtml
@model FastDynamicForms.ViewModels.RegisteredModelsViewModel
@using FastDynamicForms.Extensions

<h1>@Model.Name</h1>
@Html.ActionLink("New record", "Create", "FastDynamicForms", new { modelTypeName = Model.Name }, new { @class = "btn btn-primary" })
@Html.ActionLink("Back", "Index", "FastDynamicForms", null, new { @class = "btn btn-default" })

<table class="table table-striped">
    <thead>
        <tr>
            @foreach (var propertyName in Model.PropertyNames)
            {
                <th scope="col">
                    @Html.Partial("_LabelPartial", Model.EntityForDisplay, new ViewDataDictionary(this.ViewData) { { "PropertyName", propertyName } })
                </th>
            }
        </tr>
    </thead>
    <tbody>
        @foreach(var entities in Model.Items)
        {
            <tr>
                @foreach (KeyValuePair<System.Reflection.PropertyInfo, object> item in entities)
                {
                    <td>
                        @if (item.Key.IsPrimaryKey())
                        { 
                            @Html.ActionLink(item.Value.ToString(), "Edit", "FastDynamicForms", protocol: "", hostname: "", fragment: "",
                                routeValues: new { id = item.Value, modelTypeName = Model.Name }, htmlAttributes: null)
                        }
                        else
                        {
                            @item.Value
                        }
                    </td>
                }
            </tr>
        }
    </tbody>
</table>

Views/FastDynamicForms/_LabelPartial.cshtml
@model object

@Html.Label(this.ViewData["PropertyName"].ToString())

Views/FastDynamicForms/_NavigationPropertyPartial.cshtml
@model object
@{
    string propertyName = this.ViewData["PropertyName"].ToString();
}

<div class="form-group">
    @Html.Label(propertyName)
    @Html.DropDownList(propertyName, ((List<SelectListItem>)this.ViewData["SelectList"]), htmlAttributes: new { @class = "form-control" })
    @Html.ValidationMessage(propertyName, htmlAttributes: new { @class = "text-danger" })
</div>

Views/FastDynamicForms/_PrimaryKeyPartial.cshtml
@model object

@Html.Hidden(this.ViewData["PropertyName"].ToString())

Views/FastDynamicForms/_PropertyPartial.cshtml
@model object
@{ 
    string propertyName = this.ViewData["PropertyName"].ToString();
}

<div class="form-group">
    @Html.Label(propertyName)
    @Html.Editor(propertyName, additionalViewData: new { htmlAttributes = new { @class = "form-control" } })
    @Html.ValidationMessage(propertyName, htmlAttributes: new { @class = "text-danger" })
</div>